name: ghcr docker publish CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ashjo317
          password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build the Docker image
      run: |
       docker build . --tag ghcr.io/iie/ixiainventoryexplorer:latest
       docker push ghcr.io/iie/ixiainventoryexplorer:latest
  
